Return proper error message when SS disabled (#2911)
Currently if SS is disabled and one tries to query historical state,
you'll get error like:
```
Error: rpc error: code = Unknown desc = kv store with key KVStoreKey{0xc000c88020, acc} has not been registered in stores: panic
```

However, it is not explicit and we should return the correct error
message to indicate this was due to misconfiguration.