Update ledger-go dependency (#2798)
## Describe your changes and provide context
Currently sei-chain uses a old version of ledger-go (v0.14.1) which does
not recognize the newer range of ledger devices.

This PR simply does:
```
go get github.com/zondax/ledger-go@v1.0.1
make install
```

## Testing performed to validate your change
On the current main branch of sei-chain it's not possible to add more
modern ledger devices (in my testing i used a Ledger Nano S Plus on
Firmware 1.5.1 running Cosmos App v2.38.9).

Here's what happens when trying to add the key via `sei-chain`:
```
$ seid keys add myledger --ledger
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: LedgerHID device (idx 0) not found. Ledger LOCKED OR Other Program/Web Browser may have control of device.
Usage:
  seid keys add <name> [flags]
```

This makes sense, as only v1.0.0 and newer add the HID ids for the newer
ledger devices.

After applying the patch it works:
```
$ seid keys add myledger --ledger

- name: myledger
  type: ledger
  address: seixxx
  evm_address: ""
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"xxx"}'
  mnemonic: ""
```

I think the responsible ledger-go change is:
https://github.com/Zondax/ledger-go/commit/33eff3c25e843d4997260c5d470ceb73bf57cbf8

---------

Co-authored-by: Masih H. Derkani <m@derkani.org>